In [2]:
import numpy as np
import matplotlib as plt
import pandas as pd
import seaborn as sn

In [3]:
np.__version__

'2.2.4'

In [4]:
np.array ([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array ([2,3,4], dtype="float32") # 데이터 타입 = float

array([2., 3., 4.], dtype=float32)

In [6]:
temp = np.arange(10)
temp

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
zeroArray = np.zeros((4,3)) # 4x3 배열
zeroArray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
oneArray = np.ones((3,3,3)) # 3개, 3x3배열
oneArray

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
fullArray = np.full((3,3),3) # 배열을 3으로 다 채워주세요
fullArray

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [10]:
emptyArray = np.empty((2,3)) # 새로운 배열을 형성, 값을 초기화하지는 않음
emptyArray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
oneArray = np.ones_like((3,3,3))
#one하고 zero만 사용가능,full,empty 가능 ~_like
#배열의 차원은 그대로 가져감
oneArray

array([1, 1, 1])

In [12]:
#선형 구간의 등간격 원소를 가진 배열을 생성
#0을 포함하기에 4번으로 나눔 30/4 = 7.5 단위
np.linspace(0, 30, 5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [13]:
b = np.array([[0,1,2,3],
             [4,5,6,7],
             [8,9,10,11]], dtype='int32') 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [14]:
b.ndim #ndim = 차원을 반환

2

In [15]:
b.shape # 3x4의 배열

(3, 4)

In [16]:
b.size # 배열 안에 있는 원소의 갯수

12

In [17]:
b.itemsize 
# byte size를 나타내는 값, 원래 4가나와야 함 = >int32 , 4byte
# int64에서는 8이나옴 why?
# 64는 8byte여서... 이딴걸 왜 쓰는거지?

4

In [18]:
b.dtype

dtype('int32')

In [19]:
b = np.ones((3,3,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
b.strides # 지금 b가 int64 이기에 한줄의 =byte는8 , 한배열의 =byte는24,
          # 3배열의 =byte는 72
          # strides는 다음 데이터로 가기 위한 (전력)byte가 얼마나 필요한지를 알려줌

(72, 24, 8)

In [21]:
# 배열의 indexing
c = np.array([[0,1,2,3]])
a = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])
print(a[2][2]) # 다차원 배열의 indexing은 차원 갯수만큼 중첩시켜야 한다.
print(a[2])

10
[ 8  9 10 11]


In [22]:
temp =  np.array([[[1., 1., 1.],
                   [1., 1., 1.],
                   [1., 1., 1.]],
                 
                  [[1., 1., 1.],
                   [1., 1., 1.],
                   [1., 1., 1.]],
                 
                  [[1., 1., 1.],
                   [1., 1., 1.],
                   [1., 0., 1.]]])
print(temp.shape)
print(temp[2,1,2]) # 인덱싱은 두가지 방법으로 가능 위에꺼 써, 공부할땐 밑에 꺼
print(temp[2][2][1])

(3, 3, 3)
1.0
0.0


In [23]:
# 슬라이싱 가능
print(c[:2,1:3])
print(a[1:4:2]) #2 -> step, 건너뛰어 , range와 같은 역할
print(c[::-1])

[[1 2]]
[[4 5 6 7]]
[[0 1 2 3]]


In [24]:
print(a[:2])
print(a[1:4:2])
print(a[::-1])
print(a[-1::-2]) # 예상한대로 출력하기 위해선 인덱싱의 START, END의 부호가 같아야함

[[0 1 2 3]
 [4 5 6 7]]
[[4 5 6 7]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 8  9 10 11]
 [ 0  1  2  3]]


In [25]:
a2 = np.array([[0,1,2,3],[4,5,6,7]])
print(a2[0])
print(a2[:2,0])
print(a2[1:4:2,:2]) #컴마를 추가할 때마다 차원이 증가되는 것을 알아야함 =>2차원
print(a2[::-1,1:])

[0 1 2 3]
[0 4]
[[4 5]]
[[5 6 7]
 [1 2 3]]


In [26]:
d = np.array([[[0,1,2],[3,4,5]],
              [[6,7,8],[9,10,11]]])
d[1,:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
a = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])
print(a[0,0]) #a[0][0] = 0
print(a[2,1]) #a[2][1] = 9
print(a[[0,2],[0,1]]) # => a[(0,0),(2,1)]자리를 봐야해욧 =>array([0,9]) = ([행,열])

0
9
[0 9]


In [28]:
a_5 = a>5
print(a_5)
print("array :",a[a_5])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
array : [ 6  7  8  9 10 11]


In [29]:
a[:, [False, True, False, True]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [30]:
a[:, [0, 1, 0, 1]]

array([[0, 1, 0, 1],
       [4, 5, 4, 5],
       [8, 9, 8, 9]])

In [31]:
b= np.ones_like(a)
print(a+b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
a = np.array([[0],[10],[20],[30]])
b1 = np.array([0,1,2])
b2 = np.array([[0,1,2]])

print(a+b1)
print(a+b2)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [33]:
c = np.arange(4)
print(c + 1)
print(a + c)
d = np.zeros((2,2,4))
print(d)
print(d+c)

[1 2 3 4]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[0. 1. 2. 3.]
  [0. 1. 2. 3.]]

 [[0. 1. 2. 3.]
  [0. 1. 2. 3.]]]


In [34]:
newA = np.power(a,2) #power(배열, 몇 제곱 할지)
newA

array([[  0],
       [100],
       [400],
       [900]])

In [35]:
#axis = 0, row
#axis = 1, col

sumRow, sumCol, sumAll = np.sum(a, axis=0), np.sum(a, axis=1), np.sum(a)
sumRow, sumCol, sumAll



(array([60]), array([ 0, 10, 20, 30]), np.int64(60))

In [36]:
#shape 변환
a = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11],
              [12,13,14,15]])
# 배열 쪼개기
print(np.split(a,2)) # 2개로나눠짐 [0,1][2,3], axis = 0 가 default임
np.split(a,(1,3)) # 인덱싱 [1,2]가 기준이 됨, 3개로 나눠짐[0][1,2][3]



[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [37]:
split1, split2 = np.hsplit(a,2) # 2개로 나눠짐 [:, 0:1][:, 2:3] axis =1 (fixed)
print(split1)
print(split2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [38]:
split1, split2 = np.vsplit(a,2) # 2개로 나눠짐 [0,1][2,3] axis = 0 (fixed)
print(split1)
print(split2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [39]:
stack0 = np.stack((a,a)) # 아래로 붙음 row가 증가 , 2개를 합침 [0:4][0:4], axis=0
print(stack0.shape)
stack0

(2, 4, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [40]:
stack0 = np.stack((a,a,a))  # => (a,a,a) =차원이 느는게 아니고, 3x4x4배열이 됨
print(stack0.shape)
stack0

(3, 4, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [41]:
stack1 = np.stack((a,a), axis=1)
print(stack1.shape) # [:, 0:2, :], axis = 1 오른쪽으로 붙음
stack1

(4, 2, 4)


array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [12, 13, 14, 15]]])

In [42]:
#array = [[0,1,2,3,4],
#         [0,1,2,3,4]] => axis = 0 = vstack
#array = [[0,0],[1,1],[2,2],[3,3],[4,4]] => axis = 1 = hstack
# 왜 hstack, hsplit의 결과값이 다른가?

In [43]:
stack2 = np.vstack((a,a)) #차원을 늘리지 않고 row를 늘릴꺼면 => vstack
                          #그냥 스택은 차원이 는다.
print(stack2.shape) 
stack2

(8, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
stack3 = np.hstack((a,a)) # 차원이 늘지 않고 columns을 늘릴꺼면 => hstack
print(stack3.shape)
stack3

(4, 8)


array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])

In [45]:
print(a.shape)
a.reshape(2,8) # 2행 8열로 모양을 바꿔줌

(4, 4)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [46]:
a.reshape(8,-1000)
# 음수 값을 넣으면 row값을 지키고 columns 값이 무시당함, 자동으로 조정
a.reshape(-1,8)
# 반대도 마찬가지 , 둘다 음수는 불가
# (1,16) = flatten

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [47]:
# 여기부터 자기 자신이 바뀜 - 비휘발성
a.resize(2,8)
a
# a.resize(3,4) -> 우리는 a 변수의 함수로써 참조(reference)resize하고 있기 때문에 오류가 나지만
# 참조하지 않고 사용할 때 부족하면 값을 채워주고, 넘치면 값을 덜어낸다 => 자동으로

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [48]:
a.flatten()[0] = 100
print("flatten")
print(a) # a[0] == 0 원본은 변경x

a.ravel()[0] = 100 # 참조변수 형태가 변경
print ("ravel")
print(a) # a[0] == 100 원본 변경o


flatten
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
ravel
[[100   1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14  15]]


In [49]:
# flatten ravel 무슨 차이? 
# flatten은 copy가 된다. ~ 허상 ravel은 view 형식 비휘발성 
# 그러므로 flatten은 원본 값에 영향을 미치지 않지만,
# ravel은 수정하면 원본의 값도 바뀐다.
print(a.flatten())
print(a)
print()

print(a.ravel())
print(a)
print()

b = a.ravel() 
print("b 출력"); print(b); b[0] = 10 #ravel로 바꾼후 한번더 바꿈
print(a)
print()

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[100   1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14  15]]

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[100   1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14  15]]

b 출력
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[10  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]



In [50]:
b = np.zeros((1,2,3,4)) #4차 배열
print("before",b.shape)
b = b.transpose(0,2,1,3) #인자는 위치
print("after", b.shape)

before (1, 2, 3, 4)
after (1, 3, 2, 4)


In [51]:
d = b.T # T는 역순으로 만드는 것 => transpose에서 이어짐
print(d.shape)

(4, 2, 3, 1)


In [52]:
#squueze 1차원을 삭제
print(d.shape)
print(b.shape)
print(np.squeeze(b).shape)
print(np.squeeze(d).shape)

(4, 2, 3, 1)
(1, 3, 2, 4)
(3, 2, 4)
(4, 2, 3)


In [53]:
# newaxis
x4 = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11],
              [12,13,14,15]])
print(x4[:].shape)
print(x4[np.newaxis, :, :].shape) # newaxis 를 어디 추가 하냐에 따라 차원이 달라짐
print(x4[:, np.newaxis, :].shape) # 2차원의 4x4 에 1차원을 어디 추가하냐에 따라
print(x4[:, :, np.newaxis].shape) # shape이 바뀜

(4, 4)
(1, 4, 4)
(4, 1, 4)
(4, 4, 1)


In [54]:
x = np.arange(2*3*4)
print ("x = np.arrange(2*3*4):\n",x); print()

x = x.reshape(2,3,4)
print("첫 번째 평면 선택(plans):\n", x[0, :, :]); print()
print("첫 번째 행 선택(rows):\n", x[:, 0, :]); print()
print("첫 번째 열 선택(columns):\n", x[:, :, 0]); print()

print("x.ravel():\n", x.ravel())

x = np.arrange(2*3*4):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

첫 번째 평면 선택(plans):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

첫 번째 행 선택(rows):
 [[ 0  1  2  3]
 [12 13 14 15]]

첫 번째 열 선택(columns):
 [[ 0  4  8]
 [12 16 20]]

x.ravel():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
